#BNF+IAT 1.0 UTF-8;
!grammar call;
!slot <name>;
!slot <age>;
!slot <askPre>;
!slot <wifi>;
!slot <server>;
!slot <master>;
!slot <power>;
!slot <app>;
!slot <capacity>; 
!slot <sleep>;
!slot <picture>;
!slot <connect>;
!slot <poweroff>;
!slot <volumeup>;
!slot <volumedown>;
!slot <beginconnect>;
!slot <dance>;
!slot <story>;
!slot <nod>;
!slot <shake>;
!slot <welcome>;
!slot <rightbeck>;
!slot <leftbeck>;
!slot <stoop>;
!slot <lookup>;
!slot <leftleglifts>;
!slot <rightleglifts>;
!slot <kongfu>;
!slot <rightkick>;
!slot <leftkick>;
!slot <headdrop>;
!slot <righthandsup>;
!slot <lefthandsup>;
!slot <handsup>;
!slot <handsraise>;
!slot <actingcute>;
!slot <wink>;
!slot <smile>;
!slot <crouch>;
!slot <standup>;
!slot <deny>;
!slot <applaud>;
!slot <backwalk>;
!slot <frontwalk>;
!slot <frontlook>;
!slot <backlook>;
!slot <rightlook>;
!slot <leftlook>;
!slot <rightwalk>;
!slot <leftwalk>;
!slot <rightpunch>;
!slot <leftpunch>;
!slot <rightheadup>;
!slot <leftheadup>;
!slot <rightturn>;
!slot <leftturn>;
!slot <shakehands>;
!slot <boring>;
!slot <agree>;
!slot <sad>;
!slot <thinking>;
!slot <happy>;
!slot <greet>;
!slot <laugh>;
!slot <hearttired>;
!slot <happynewyear>;
!slot <hum>;
!slot <grievance>;
!slot <perfect>;
!slot <sharp>;
!slot <rock>;
!slot <tfboy>;
!start <askStart>;
<askStart>:([<askPre>]<name>)|[<askPre>]<age>|[<askPre>]<wifi>|[<askPre>]<server>|[<askPre>]<master>|<power>|<app>|[<askPre>]<capacity>|<sleep>|<picture>|<connect>|<poweroff>
|<volumeup>|<volumedown>|<beginconnect>|<dance>|<story>|<nod>|<shake>|<welcome>|<rightbeck>|<leftbeck>|<stoop>|<lookup>|<leftleglifts>|<rightleglifts>
|<kongfu>|<rightkick>|<leftkick>|<headdrop>|<righthandsup>|<lefthandsup>|<handsup>|<handsraise>|<actingcute>|<wink>|<smile>|<crouch>|<standup>|<deny>|<applaud>|
<backwalk>|<frontwalk>|<frontlook>|<backlook>|<rightlook>|<leftlook>|<rightwalk>|<leftwalk>|<rightpunch>|<leftpunch>|<rightheadup>|<leftheadup>|
<rightturn>|<leftturn>|<shakehands>|<boring>|<agree>|<sad>|<thinking>|<happy>|<greet>|<laugh>|<hearttired>|<happynewyear>|<hum>|<grievance>|<perfect>|<sharp>|<rock>|<tfboy>;

<askPre>:请问|我想知道|告诉我;
<name>:你叫什么名字|你叫什么|你的名字叫什么;
<age>:今年你多大了|你今年多大了|今年你几岁了|你今年几岁了;
<wifi>:你现在连的是哪个Wifi？|你在连哪个Wifi？|你连的是哪个Wifi？|你正在连哪个Wifi？|你现在在连哪个Wifi？|哪个Wifi是你现在连的？|你现在连的是什么Wifi？|你在连什么Wifi？|你连的是什么Wifi？|你正在连什么Wifi？|你现在在连什么Wifi？|什么Wifi是你现在连的？;
<server>:你登录了吗|你已经登录了吗？|你登录了没？|告诉我你登录了吗？|我想知道你登录没？|你是不是已经登陆了|你登录服务器了吗？|你成功登录服务器了吗？|你已经登录服务器了吗？;
<power>:你现在的电量是多少？|你还有多少电?|你还有多少电量？|你现在还有多少电量？|你现在还有多少电？|告诉我你还有多少电量|告诉我你还有多少电|告诉我你现在有多少电量|告诉我你现在有多少电|我想知道你有多少电量|我想知道你有多少电|你还剩多少电量？|你还剩多少电|你的电量还剩多少？|你的电还剩多少|你还有百分之多少的电量？|你还剩百分之几的电量？|你还剩百分之几的电？|你现在是满电吗？|检查电量|检查剩余电量|检查剩余电量还有多少;
<master>:你被绑定了吗？|你被绑定了没？|你已经被绑定了？|谁绑定你的？|你被谁绑定了？|是谁绑定了你？|告诉我谁绑定你了？|告诉我是谁绑定你了？|告诉我是谁绑定了你？|查一下谁绑定你了？|查一查谁绑定了你？;
<capacity>:你还有多少容量？|你还有多少存储空间?|你还有多少储存空间?|你还剩多少存储空间？|你还剩多少储存空间?|
你还可以放多少东西|你还有多少空间？|你还有多少容量?|你还可以存储多少东西？|你还有多少内存？;
<sleep>:去休息吧|去休息|去睡吧|睡吧|休息下吧|你该去休息了|累了就去睡吧|你该去休息了|累了就休息吧;
<connect>:你联网了吗？|你已经联网了吗？|你联网了没？|查一下你有没联网|你有没联网|你没有联网吗？|你连上网了吗？|你连接网络了吗？|你现在是联网了吗？|你现在是已经联网了吗？;
<app>:
你正在用的是哪个应用？|
你现在在用哪个应用？|
你现在正在用的是哪个应用？|
你在用哪个应用？|
哪个应用是你在用的？|
哪个应用是你现在在用的？|
你正在运行哪个应用？|
你正在运行的是哪个应用？|
你正在用的是什么应用？|
你现在在用什么应用？|
你现在正在用的是什么应用？|
你在用什么应用？|
什么应用是你在用的？|
什么应用是你现在在用的？|
你正在运行什么应用？|
你正在运行的是什么应用？|
你正在用的是哪个APP？|
你现在在用哪个APP？|
你现在正在用的是哪个APP？|
你在用哪个APP？|
哪个APP是你在用的？|
哪个APP是你现在在用的？|
你正在运行哪个APP？|
你正在运行的是哪个APP？|
你正在用的是什么APP？|
你现在在用什么APP？|
你现在正在用的是什么APP？|
你在用什么APP？|
什么APP是你在用的？|
什么APP是你现在在用的？|
你正在运行什么APP？|
你正在运行的是什么APP？|
你用的是哪个应用啊？;
<picture>:我想看最近拍的照片|我要看最近拍的照片|我想要看最近拍的照片|给我看最近拍的照片|有哪些是最近的照片|哪些是最近的照片|我想看最新拍的照片|我要看最新拍的照片|我想要看最新拍的照片|给我看最新拍的照片|有哪些是最新的照片|哪些是最新的照片|有新的照片吗？|
有新照片吗？|可以给我看新照片吗？|能让我看新照片吗？;
<poweroff>:你关机吧|关机;
<volumeup>:大声点|大声一点|大点声|再大声点|再大点声|音量大一点|我听不到你说话了|太小声了|增大音量|声音大一点;
<volumedown>:小声点|小声一点|小点声|音量小一点|你太吵了|太大声了|减小音量|再小声点|再小点声|声音小一点;
<beginconnect>:连接网络|给我联网|联网吧|你联网吧|帮我联网|启动联网流程|进入联网流程|快帮我联网|我要联网;
<dance>:跳舞|跳个舞吧|跳个舞呗|给我跳个舞|我想看你跳舞|给我们跳舞|给我们跳个舞|来跳个舞|我想看你跳舞|我想看你跳段舞蹈|我想看你表演跳舞|我想看你表演舞蹈|我想看你表演一段舞蹈|我想看你来段舞蹈|我想看你展示舞蹈|我想看你跳一段舞蹈|我想看你展示一下舞步|我想看你展示一下舞姿|跳个舞|跳舞|跟我一起跳舞|表演跳舞|跳一下舞|我想看你展示一下你的舞姿|表演跳舞;
<story>:讲个故事|讲个故事吧|讲个故事呗|我想听故事|给我讲个故事呗|给我讲个故事|我想听故事|我想听故事|我们想听故事|我们大家想听故事|大家想听故事|我要听故事|我们要听故事|我们大家要听故事|大家要听故事|我想要听故事|我们想要听故事|我们大家想要听故事|大家想要听故事|讲个故事|请讲个故事|请你讲个故事|麻烦讲个故事|麻烦你讲个故事|随便讲个故事|说个故事|我想要听故事|请说个故事|请你说个故事|麻烦说个故事|麻烦你说个故事|随便说个故事;
<nod>:点点头|点一下头|点头|点个头;
<shake>:摇摇头|甩甩头|摇一下头|摇头;
<welcome>:欢迎客人|欢迎新朋友|你好|问个好|来欢迎一下;
<rightbeck>:挥一下右手|挥右手|向右边打招呼|朝右边打招呼|往右边打招呼;
<leftbeck>:挥一下左手|挥左手|向左边打招呼|朝左边打招呼|往左边打招呼;
<stoop>:鞠个躬|你节操掉了|肥皂掉了|鞠躬|弯腰;
<lookup>:抬起头|抬头|抬起你的头|天上有星星|抬一下头;
<leftleglifts>:抬起左脚|抬左脚;
<rightleglifts>:抬起右脚|抬右脚;
<kongfu>:表演功夫|打功夫|我想看功夫|你会功夫吗;
<rightkick>:右踢腿|向右踢腿|往右踢腿;
<leftkick>:左踢腿|向左踢腿|往左踢腿;
<headdrop>:低下头|低头|把头低下;
<righthandsup>:举起右手|举右手|举起你的右手|把右手举起来;
<lefthandsup>:举起左手|举左手|举起你的左手|把左手举起来;
<handsup>:举起你的双手|举双手|举起双手|举起手来;
<handsraise>:抬起双手|抬双手;
<actingcute>:卖个萌|你好可爱|卖萌;
<wink>:对我放电|放个电|眨下眼睛|眨眼睛;
<smile>:笑一个|给我笑一下;
<crouch>:蹲下|往下蹲|朝下蹲|向下蹲|休息|休息一下|坐下;
<standup>:站起来|蹲下站起|起来;
<deny>:你好笨|你好蠢|你在说谎吧|你是不是心虚;
<applaud>:拍个手|鼓个掌|我棒吗;
<backwalk>:往后退|向后退|朝后退|往后移|向后移|后移;
<frontwalk>:向前进|往前走|向前走|往前进;
<frontlook>:看前方|目视前方|看前面|向前看|往前看|朝前看|头转正;
<backlook>:向后走|往后面走|向后边走|往后走;
<rightlook>:向右看|朝右看|往右看|看右边|头向右看|头朝右看|头往右看;
<leftlook>:向左看|向左边看|往左看|往左边看|朝左看|朝左边看|看左边|头向左看|头向左边看|头朝左看|头朝左边看|头往左看|头往左边看;
<rightwalk>:向右走|往右走|向右边走|向右移|朝右移|往右移;
<leftwalk>:向左走|往左走|向左边走|向左移|朝左移|往左移|左移;
<rightpunch>:右出拳|出右拳|右击;
<leftpunch>:左出拳|出左拳|左击;
<rightheadup>:右抬头|看右上方|朝右上方看|向右上方看|往右上方看;
<leftheadup>:看左上方|朝左上方看|向左上方看|往左上方看|左抬头;
<rightturn>:向右转|右转|往右转|朝右转;
<leftturn>:向左转|往左转|朝左转|左转;
<shakehands>:我们做好朋友吧|你是我的好朋友吗|来握个手|握手;
<boring>:好无聊阿|好闷;
<agree>:赞同|你同意吗？|我说的对吗？|对不对？;
<sad>:我不喜欢你了|伤心|你好烦|不开心吗？|你不开心吗？;
<thinking>:在想什么？|你在思考什么？|你在干嘛？;
<happy>:你开心吗？|今天心情怎么样？;
<greet>:你好|你好啊|你好呀|雷猴啊|我走了|我走啦|我要走啦|走啦|我出门啦|我要出门啦|出门啦|我要出门啦|我要出去了|我要走啦|我回来了|我回来啦|回来啦|再见|拜拜|白白|再见啦|拜拜啦|白白啦
|早啊|早安|早上好|中午好|午安|晚安|晚安啦|阿尔法|阿法|你好厉害|你好厉害啊|你好厉害呀|厉害|我不开心|不开心|宝宝不开心|不高兴|我好高兴|我好开心|好开心|我好开心啊|我好开心呀|谢谢|感谢
|谢谢你|谢谢你啊|谢谢你呀|好感谢你呀|对不起|对不起啊|真对不起|抱歉|抱歉啊|真抱歉|不好意思|不好意思啊|真不好意思|加油|加油啊|加油呀|要加油啊|要加油呀|我好喜欢你|喜欢你|好喜欢你
|吃了饭没|吃饭了吗|你吃饭了吗|你吃饭了没|你吃了饭没|你吃了饭吗|吃了吗|你最喜欢什么|你最喜欢啥|你喜欢啥|你喜欢什么|喜欢啥|喜欢什么|新年快乐|新年快乐啊|新年快乐呀|新年快乐哟|新年快乐哦
|祝你新年快乐|祝你新年快乐啊|祝你新年快乐呀|祝你新年快乐哟|祝你新年快乐哦|圣诞快乐|圣诞快乐啊|圣诞快乐呀|圣诞快乐哟|圣诞快乐哦|祝你圣诞快乐|祝你圣诞快乐啊|祝你圣诞快乐呀|祝你圣诞快乐哟
|祝你圣诞快乐哦|春节快乐|春节快乐啊|春节快乐呀|春节快乐哟|春节快乐哦|祝你春节快乐|祝你春节快乐啊|祝你春节快乐呀|祝你春节快乐哦|祝你春节快乐哟|生日快乐|生日快乐啊|生日快乐呀|生日快乐哟
|生日快乐哦|祝你生日快乐|祝你生日快乐啊|祝你生日快乐呀|祝你生日快乐哟|祝你生日快乐哦|国庆节快乐|国庆节快乐啊|国庆节快乐呀|国庆节快乐哟|国庆节快乐哦|祝你国庆节快乐|祝你国庆节快乐啊
|祝你国庆节快乐呀|祝你国庆节快乐哟|祝你国庆节快乐哦|今天好热啊|好热啊|天气好热啊|现在好热啊|今天好冷啊|好冷啊|现在好冷啊|天气好冷啊|今天天气真好|天气真好|天气好好啊|现在天气好好啊
|今天雨好大|雨好大啊|外面雨好大啊|外面下好大雨|今天雪好大|雪好大啊
|外面雪好大啊|外面下好大雪|今天雾霾好大|雾霾好大啊|外面雾霾好大啊|外面好大雾霾啊|做个自我介绍吧|来个自我介绍|来个自我介绍吧|做个自我介绍呗|给大家做个自我介绍呗|你叫什么名字|你叫啥|你是男的还是女的
|你是男生还是女生|你是男是女|你是男孩还是女孩|你多大了|你多少岁了|你几岁了|你多大了啊
|你年龄多少|你多高|你多高啊|你身高多少|多高啊你|你多重|你体重多少|你体重多重|你值多少钱|你多少钱啊|多少钱能买你啊|你卖多少钱啊|厉害|你是什么|你是机器人吗|你是啥|你会做什么|你能做啥|你能做什么
|你能干啥|你能干什么|你从哪里来|你来自哪里|你来自哪里啊
|你来自哪|你从哪里来啊|帮我算算今天的运气|帮我看看今天的运气|我今天运气怎么样|我今天的运气怎么样|今天我的运气怎么样|你知道优必选吗？|知道优必选吗？|你知道优必选这个公司吗？|知道优必选这个公司吗？
|你听过优必选吗？|听过优必选吗？|你知道机器人爸爸吗？|知道机器人爸爸吗？|你知道机器人爸爸是谁吗？|知道机器人爸爸是谁吗？|你听过机器人爸爸吗？|听过机器人爸爸吗？|你知道机器人吗？|知道机器人吗？
|你知道机器人是啥吗？|知道机器人是啥吗？|你知道机器人是什么吗？|知道机器人是什么吗？|你听过机器人吗？|听过机器人吗？;
<laugh>:大笑|来个大笑|来个周星驰的笑声|来个周星驰的大笑|我想听周星驰的大笑;
<hearttired>:感觉身体被掏空|心好累;
<happynewyear>:恭喜发财红包拿来|新春大吉|新春快乐|恭喜发财;
<hum>:不理你了|哼一个;
<grievance>:好委屈|委屈|不理你了;
<perfect>:表演一下完美|表演完美|来个王祖蓝的完美;
<sharp>:你这么厉害你咋不上天呢|你咋不上天|你怎么不上天;
<rock>:一起摇摆|摇摆|让我们摇摆|让我们一起摇摆;
<tfboy>:左手右手慢动作|左手右手一个慢动作|你知道TFBOYS吗|TFBOYS|掏粪男孩|小鲜肉|你喜欢TFBOYS吗|跟着我左手右手一个慢动作;