/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ubtechinc_alpha_jni_LedControl */

#ifndef _Included_com_ubtechinc_alpha_jni_LedControl
#define _Included_com_ubtechinc_alpha_jni_LedControl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ubtechinc_alpha_jni_LedControl
 * Method:    open
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_ubtechinc_alpha_jni_LedControl_open
  (JNIEnv *, jclass);

/*
 * Class:     com_ubtechinc_alpha_jni_LedControl
 * Method:    close
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_ubtechinc_alpha_jni_LedControl_close
  (JNIEnv *, jclass);

/*
 * Class:     com_ubtechinc_alpha_jni_LedControl
 * Method:    ledSetOn
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_ubtechinc_alpha_jni_LedControl_ledSetOn
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_ubtechinc_alpha_jni_LedControl
 * Method:    ledSetOFF
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_ubtechinc_alpha_jni_LedControl_ledSetOFF
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_ubtechinc_alpha_jni_LedControl
 * Method:    ledSetEye
 * Signature: (IIIIIIII)Z
 */
JNIEXPORT jboolean JNICALL Java_com_ubtechinc_alpha_jni_LedControl_ledSetEye
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_ubtechinc_alpha_jni_LedControl
 * Method:    ledSetHead
 * Signature: (IIIIIIII)Z
 */
JNIEXPORT jboolean JNICALL Java_com_ubtechinc_alpha_jni_LedControl_ledSetHead
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_ubtechinc_alpha_jni_LedControl
 * Method:    ledSetMouth
 * Signature: (IIIII)Z
 */
JNIEXPORT jboolean JNICALL Java_com_ubtechinc_alpha_jni_LedControl_ledSetMouth
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
